### ISSUE TITLE
emmet-language-server

### ISSUE THREAD

**Issue by MartinAskestad** [yegappan/lsp#368]
For omni completion when writing html and emmet, [emmet-language-server](https://github.com/olrtg/emmet-language-server) is a great help. Here is an example config for getting it to work.

```vim
call LspAddServer([#{name: 'emmet',
                 \   filetype: 'html',
                 \   path: '/usr/local/node_modules/.bin/emmet-language-server',
                 \   args: ['--stdio'],
                 \ }])
```

**Comment by yegappan** [comment]
Thanks.  I have updated the wiki with the above sample code for adding the emmet language server.

**Comment by Shane-XB-Qian** [comment]
@yegappan do you mind making multiple-server configuring (for same ft) with features switches (true or false) work again? or it was not working ever, but seems it was mergered be part of our lsp code base already, so perhaps need to make it work (though seems high complexity).

// for now seems only first configured server's features counted.
// supposed nothing impacted for now, just I found it was failed, so jump in to give you a message, take your time anyway.

--
shane.xb.qian

**Comment by yegappan** [comment]
I tested enabling few features in one language server and other features in another language server with two language servers registered for the same filetype.  From the logs, I can see that this works properly.  Do you have the list of steps to reproduce the problem?  Which language servers are you using?  Which features did you try enabling and disabling in the language servers?

**Comment by Shane-XB-Qian** [comment]
you can try pylsp with hover/completion/signature features disabled (false) while pyright with these enabled (true),
you can see hover etc always from pylsp (and disabled) which pyright not really took over the features functionality.
// or here if two for html, it should be same case.
// though i do not recommend this, since it would raise complexity of code and functionality much, but there already.

**Comment by yegappan** [comment]
I tried to reproduce this issue with both the pylsp and pyright language servers registered for python files.  I disabled the hover/completion/signature features for pylsp and enabled for the pyright server.  From the debug logs, I can see that these features are handled by the pyright language server and not by the pylsp server. 

I also tried to reproduce this issue with the typescript-language-server and the deno server for typescript files.  I couldn't reproduce this issue.

Can you enable the debug logs for both the language servers and run the ":LspHover" command and see which server is handling the request?  Can you also show how you are registering the language servers?

**Comment by Shane-XB-Qian** [comment]
um, how you can get that debug log? it should be failed immediately when feature check:
`Error: Language server for "python" file type supporting "hover" feature is not found`

// not much specially, except features option
// `'features': { 'hover': v:false }` for pylsp
// `'features': { 'hover': v:true }`  for pyright

-- 
shane.xb.qian

**Comment by yegappan** [comment]
Can you attach the complete call to the LspAddServer() function to register the pylsp and pyright servers with all the arguments?

**Comment by Shane-XB-Qian** [comment]
same like in the wiki, nothing specially except features option.
// according to basic ps cmd, pyright did not even start, but only pylsp, but since it disabled hover feature, so none!
a.k.a :
`Error: Language server for "python" file type supporting "hover" feature is not found` this err was a correct prompt.

-- 
shane.xb.qian

**Comment by Shane-XB-Qian** [comment]
if still no clue to you, then let it be..
// it does not bother me actually :smile: and i did not recommended this feature too.
// but just felt like a similar ticket at this repo startup or https://github.com/yegappan/lsp/issues/98 this one. 

-- 
shane.xb.qian

**Comment by yegappan** [comment]
Can you try to reproduce the issue with the latest plugin version?

**Comment by Shane-XB-Qian** [comment]
> Can you try to reproduce the issue with the latest plugin version?

i think your latest commits (some mins ago) was not necessary or didnot help something:
1, or even worse, since it mixed to use 'augroup' and 'aupat' in this repo, make more confused much;
2, these buf/feature check etc seems would not make something different, eventually err prompt if no
3, specially i have no confident to verify all your change(these commits) i donot see it was bug fix

IMO:
a, that inlay hints #357 my pr worked, but just i guess was a vim bug to make 'once' be failed.
b, this multiple-servers features seems rare and conner case let it be is ok!  <---
   i guess it was init timing issue, it would be failed in some specific case
   but mainly it should be worked as you said, just vim9 had some tiny diff..
c, if you have time, #338 maybe more valuable
   // though not only py env dyn change issue,
   // e.g go.mod (and/or its import pkg) changed, seems re-effect the changes seems do was an issue,
   // 'lspserver restart' seems not help some.
   // i was observing as well, no clue so far.

-- 
shane.xb.qian
